baseURL = "https://example.com"
languageCode = "en-us"
title = "Kexin's Blog"
theme="archie"
copyright = "Â© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 2

[params]
favicon = "https://github.com/HuangKexinSpace/HuangKexinSpace.github.io/blob/master/assets/kexin-icon.png?raw=true"
	mode="auto"
	useCDN=false
	subtitle = """Hello, this is Kexin. I am a master's student ğŸ‘©â€ğŸ“ at Southern University of Science and Technology, focus on Human-Computer Interaction. 
Here, I document my [projects](https://huangkexinspace.github.io/project/) and [learning progress](https://huangkexinspace.github.io/posts/). Feel free to read [about](https://huangkexinspace.github.io/about/) me to get more info. 
 ğŸ‘‡ The following are my latest updates on projects and learning."""

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/HuangKexinSpace"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:functionhkx@gmail.com"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Post"
url = "/posts"
weight = 3

[[menu.main]]
name = "Project"
url = "/project"
title = "all projects"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

