baseURL = "https://example.com"
languageCode = "en-us"
title = "Kexin's Blog"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 5

[params]
favicon = "https://github.com/HuangKexinSpace/HuangKexinSpace.github.io/blob/master/assets/kexin-icon.png?raw=true"
	mode="auto"
	useCDN=false
	subtitle = """Hello, this is Kexin. I learn, research, develop, design and record.
	（新的个人页面正在用别的模板重构中，当前页面即将弃用，最后在这边更新游戏开发日记）







	
	"""

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/HuangKexinSpace"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:functionhkx@gmail.com"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Project"
url = "/projects"
title = "all projects"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

